import type { GetServerSideProps } from 'next'
import Head from 'next/head'
import StockItems from '../components/StockItems/StockItems'
import styles from '../styles/Home.module.css'

type Props = {
  data: {
    instruments: []
  }
}

const Home = ({ data }: Props) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <StockItems stockItems={data.instruments} />
      </main>
    </div>
  )
}


export const getServerSideProps: GetServerSideProps = async () => {
  const res = await fetch(`http://localhost:3000/stocks/securities/web/markets/stockmarkets/AEX`);
  console.log(res)
  const data = JSON.parse((await res.text()).slice(5));
  
  return { props: { data } };
}

export default Home
